### ISSUE TITLE
Install Python 3.7 and missing Python libraries

### ISSUE THREAD

**Issue by olemis** [skycoin/pyskycoin#81]
Since `Python=3.7` is in Travis build matrix , it's the right time to include it in CLI and DIND dev Docker images . Besides packages `pytest` and `pytest-runner` should be installed as well, preferably via `apt` else using `pip`.

**Comment by stdevYuniers** [comment]
On Travis too I have added more packages to installation and [made some changes](https://github.com/simelo/pyskycoin/blob/stdevYuniers_t76_dev_image_with_docker_daemon/.travis.yml#L84) because `root python env` become with a different Python version of our Travis matrix.

**Comment by olemis** [comment]
@stdevYuniers 👍 ... is there a PR anywhere for this issue ?

**Comment by stdevYuniers** [comment]
> @stdevYuniers +1 ... is there a PR anywhere for this issue ?

Since I will fix it under [simelo/stdevYuniers_t76_dev_image_with_docker_daemon](https://github.com/simelo/pyskycoin/tree/stdevYuniers_t76_dev_image_with_docker_daemon)  branch, a PR [has been created](https://github.com/skycoin/pyskycoin/pull/80) .

Travis build fail due strange error, [see log](https://travis-ci.org/simelo/pyskycoin/jobs/461136272#L1888).

**Comment by olemis** [comment]
fixed by #80
